### ISSUE TITLE
A copy

### ISSUE THREAD

**Issue by LuoZijun** [casey/oi#3]
https://github.com/LuoZijun/oioioi

Just for fun :)

**Comment by casey** [comment]
Very cool!

I'm experimenting a little bit with how best to add source position information to an error, but I'm not sure what the best way is. To experiment, I made this crate that encapsulates a source position, and which implements `Location`: https://github.com/casey/position

PS Obviously, my crate is totally inspired / shamelessly copied from your crate. I hope you don't mind, and many thinks fo the inspiration

**Comment by LuoZijun** [comment]
Good job :) 👍
